import { router, json, error, ai, db } from '@appdeploy/sdk';

type SalonData={name?:string;category?:string;address?:string;phone?:string;website?:string;rating?:number;reviewCount?:number;hours?:string[];description?:string;services?:string[];reviews?:string[]};
type SiteRecord={name:string;category:string;address:string;phone:string;website:string;rating:number;reviewCount:number;hours:string[];description:string;services:string[];reviews:string[];mapsUrl:string;createdAt:string;missing:string[]};
const defaults=['قص وتصفيف الشعر','صبغات وعلاجات الشعر','مكياج وتجهيز مناسبات','العناية بالبشرة','الأظافر والسبا'];
const clean=(v:unknown)=>typeof v==='string'?v.trim():'';
const siteSchema={type:'object',properties:{name:{type:'string'},category:{type:'string'},address:{type:'string'},phone:{type:'string'},website:{type:'string'},rating:{type:'number'},reviewCount:{type:'number'},hours:{type:'array',items:{type:'string'}},description:{type:'string'},services:{type:'array',items:{type:'string'}},reviews:{type:'array',items:{type:'string'}}},required:['name']};
const demo:SalonData={name:'لومي بيوتي لاونج',category:'صالون تجميل نسائي',address:'طريق الأمير سلطان، الخبر، المملكة العربية السعودية',phone:'0551234567',website:'',rating:4.8,reviewCount:327,hours:['السبت–الخميس: 10:00 ص – 10:00 م','الجمعة: 2:00 م – 10:00 م'],description:'تجربة جمال هادئة تجمع العناية بالشعر والبشرة والأظافر في مساحة أنيقة.',services:['قص وتصفيف الشعر','صبغات وعلاجات الشعر','مكياج المناسبات','العناية بالبشرة','الأظافر والسبا'],reviews:['شغل مرتب وتعامل راقٍ والمكان جميل.','الحجز سهل والموعد كان منظم جدًا.','من أفضل التجارب، اهتمام واضح بالتفاصيل.']};
function toRecord(data:SalonData,mapsUrl:string):SiteRecord{const services=Array.isArray(data.services)?data.services.map(clean).filter(Boolean).slice(0,9):[];const reviews=Array.isArray(data.reviews)?data.reviews.map(clean).filter(Boolean).slice(0,6):[];const missing:string[]=[];if(!clean(data.phone))missing.push('رقم التواصل');if(!services.length)missing.push('قائمة الخدمات الرسمية');missing.push('صور المشغل');return{name:clean(data.name)||'مشغل تجميل',category:clean(data.category)||'صالون تجميل',address:clean(data.address),phone:clean(data.phone),website:clean(data.website),rating:Number(data.rating)||0,reviewCount:Number(data.reviewCount)||0,hours:Array.isArray(data.hours)?data.hours.map(clean).filter(Boolean).slice(0,14):[],description:clean(data.description),services:services.length?services:defaults,reviews,mapsUrl,createdAt:new Date().toISOString(),missing:[...new Set(missing)]}}

export const handler=router({
 'POST /api/generate':[async c=>{const body=(c.body||{}) as {mapsUrl?:string;demoMode?:boolean};const demoMode=body.demoMode===true;const mapsUrl=clean(body.mapsUrl);if(!demoMode&&!/^https?:\/\/(maps\.app\.goo\.gl|www\.google\.[^/]+\/maps|google\.[^/]+\/maps|goo\.gl\/maps)/i.test(mapsUrl))return error('أدخل رابط Google Maps صحيح',400);let data:SalonData=demo;let source=mapsUrl;if(!demoMode){try{const scraped=await ai.scrape({url:mapsUrl});if(scraped.status>=400||scraped.text.trim().length<30)return error('تعذر قراءة صفحة Google Maps العامة',502);const extracted=await ai.extract({content:scraped.text,prompt:'استخرج بيانات هذا النشاط التجاري كما تظهر في المصدر فقط. ركز على اسم المشغل، التصنيف، العنوان، الهاتف، الموقع الإلكتروني، التقييم، عدد المراجعات، ساعات العمل، وصف مختصر، الخدمات المذكورة، ومقتطفات مراجعات حقيقية إن ظهرت. لا تخترع أسعارًا أو معلومات غير موجودة.',schema:siteSchema,thinkingMode:'FAST',maxRetries:2,maxTokens:1600});data=extracted.data as SalonData}catch(err){const rpc=err as {statusCode?:number};console.warn('maps extraction failed',rpc.statusCode||'unknown');return error('لم نستطع استخراج بيانات هذا الرابط تلقائيًا. جرّب رابط Google Maps المباشر للمكان.',502)}}else source='https://maps.google.com/?q=demo-salon';const record=toRecord(data,source);const[id]=await db.add('salon_sites',[record]);if(!id)return error('تعذر حفظ الموقع',500);return json({site:{id,...record}},201)}],
 'GET /api/site/:id':[async c=>{const[site]=await db.get<SiteRecord>('salon_sites',[c.params.id]);return site?json({site:{id:c.params.id,...site}}):error('الموقع غير موجود',404)}],
 'POST /api/bookings':[async c=>{const b=(c.body||{}) as {siteId?:string;name?:string;phone?:string;service?:string;date?:string;time?:string};const siteId=clean(b.siteId),name=clean(b.name),phone=clean(b.phone),service=clean(b.service),date=clean(b.date),time=clean(b.time);if(!siteId||!name||!/^05\d{8}$/.test(phone)||!service||!date||!time)return error('بيانات الحجز غير مكتملة',400);const[site]=await db.get<SiteRecord>('salon_sites',[siteId]);if(!site)return error('الموقع غير موجود',404);const{items}=await db.list<{siteId:string;date:string;time:string;status:string}>('salon_bookings',{filter:{siteId,date,time}});if(items.some(x=>x.status!=='ملغي'))return error('هذا الموعد محجوز بالفعل',409);const rec={siteId,name,phone,service,date,time,status:'جديد',ref:'MS-'+Math.random().toString(36).slice(2,7).toUpperCase(),createdAt:new Date().toISOString()};const[id]=await db.add('salon_bookings',[rec]);if(!id)return error('تعذر حفظ الحجز',500);return json({ok:true,booking:{id,...rec}},201)}]
});